version: '3.8'

services:
  app:
    image: node:22-alpine
    container_name: nestjs-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=nestjs
      - JWT_SECRET=somesecret
    restart: on-failure:5
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nestjs
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
